language: python
python:  # https://devguide.python.org/#status-of-python-branches
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  #flake8 currently fails with nightly
  #- "nightly"
env:  # https://www.djangoproject.com/download/
  - DJANGO=3.0.4 DRF==3.11.0
  - DJANGO=3.0.4 DRF==3.10.3
  - DJANGO=3.0.4 DRF==3.9.4
  - DJANGO=2.2.11 DRF==3.11.0
  - DJANGO=2.2.11 DRF==3.10.3
  - DJANGO=2.2.11 DRF==3.9.4
install:
  # Build/test dependencies
 - pip install -r requirements.txt -r requirements-dev.txt
 - pip install Django==$DJANGO djangorestframework=$DRF
script:
  - ./test.py code-quality
  - ./test.py test
  - python setup.py install
matrix:
    exclude:
        - env: DJANGO=3.0.4 DRF==3.11.0
          python: "3.5"
        - env: DJANGO=3.0.4 DRF==3.10.3
          python: "3.5"
        - env: DJANGO=3.0.4 DRF==3.9.4
          python: "3.5"
        # exclude all Django-3.0/DRF-3.9 combos, DRF-3.9 includes django.utils.six
        - env: DJANGO=3.0.4 DRF==3.9.4
          python: "3.6"
        - env: DJANGO=3.0.4 DRF==3.9.4
          python: "3.7"
        - env: DJANGO=3.0.4 DRF==3.9.4
          python: "3.8"
        - env: DJANGO=3.0.4 DRF==3.9.4
          python: "3.9"
